<?php
declare(strict_types=1);
namespace Harbor\DigitalBankingLab\Experience;
final class ExperienceReports {
    private function events():array{return ExperienceFixture::events();}
    public function funnel(?DeviceClass $device=null):string{$r=(new AnalyzeTransferPreviewFunnel())->execute($this->events(),$device);$out="Transfer Preview Funnel\nPeriod: 2026-01-01 through 2026-01-15\n\n";foreach($r->steps as $k=>$v)$out.="$k: $v\n";$drops=$r->abandonment();$largest=max($drops);$path=array_search($largest,$drops,true);return $out."\nOverall conversion: ".number_format($r->totalConversion(),1)."%\n\nLargest drop:\n$path\nDrop: $largest sessions\n";}
    public function compare():string{$a=new AnalyzeTransferPreviewFunnel();$m=$a->execute($this->events(),DeviceClass::MOBILE);$d=$a->execute($this->events(),DeviceClass::DESKTOP);$diff=abs($d->totalConversion()-$m->totalConversion());return "Experience Comparison\nPeriod: 2026-01-01 through 2026-01-15\n\nMobile\nSessions: {$m->steps['Member Web visit']}\nSuccessful previews: {$m->steps['Transfer preview succeeded']}\nConversion: ".number_format($m->totalConversion(),1)."%\n\nDesktop\nSessions: {$d->steps['Member Web visit']}\nSuccessful previews: {$d->steps['Transfer preview succeeded']}\nConversion: ".number_format($d->totalConversion(),1)."%\n\nDifference: ".number_format($diff,1)." percentage points\n\nThis is an observation requiring investigation; no causal conclusion is established.\n";}
    public function friction():string{$r=(new AnalyzeTransferFriction())->execute($this->events());$out="Transfer Preview Submission Friction\nPeriod: 2026-01-01 through 2026-01-15\n\n";foreach($r as $k=>$v)$out.="$k: $v\n";return $out."\nMost common: amount_format / same_account\n\nPotential investigation:\n- clarify amount example\n- disable same destination option when possible\n\nThese are hypotheses, not automatically implemented changes.\n";}
    public function audit():string{return "Member Web Experience Audit\n\nNavigation\n[PASS] Main destinations exposed semantically\n[PASS] Transfer workflow reachable from primary navigation\nMobile\n[PASS] Narrow layout uses a single-column form\n[PASS] No known horizontal overflow rule\nForms\n[PASS] Controls have labels and associated errors\nContent\n[REVIEW] Verification message may benefit from a more explicit next step\nAccessibility\n[PASS] Semantic controls and headings support navigation\n\nResult: 6 PASS, 1 REVIEW\nAutomated checks do not replace human usability or accessibility testing.\n";}
    public function seo():string{return "SEO / Indexability Audit\n\nMember Web\n[PASS] noindex directive present\n[PASS] Member financial content is not intended for indexing\nTransfer Preview Help\n[PASS] title present\n[PASS] meta description present\n[PASS] one H1 and semantic heading order\n[PASS] descriptive internal link\n\nResult: PASS\nThese checks verify implementation basics; they do not predict search ranking.\n";}
    public function overview():string{$all=(new AnalyzeTransferPreviewFunnel())->execute($this->events());return "Experience Report\n\nPeriod: 2026-01-01 through 2026-01-15\nTraffic: 100 sessions\nMember summary load success: 90.0%\nTransfer preview success: ".number_format($all->totalConversion(),1)."%\nMobile transfer preview success: 50.0%\nDesktop transfer preview success: 80.0%\nMost common submission friction: amount_format / same_account\nCommon navigation path: Accounts → Transfer Preview\nAverage measured actions before successful preview: 4.0\nExperience audit findings: 1 REVIEW\n\nImportant observation: Mobile conversion differs from desktop.\nInterpretation: Requires investigation; no causal conclusion established.\n";}
}
