<?php
declare(strict_types=1);
require dirname(__DIR__,2).'/bootstrap.php';
use Harbor\DigitalBankingLab\Delivery\{ChangeRiskAssessment,ChangeSet,DeploymentReadinessCheck,GitRepositoryInspector,ReviewScenarioCatalog};
$tests=[];$test=static function(string $n,callable $b)use(&$tests){$tests[$n]=$b;};$assert=static function(bool $v,string $m='assertion failed'){if(!$v)throw new RuntimeException($m);};
$test('change paths are classified and ordered deterministically',function()use($assert){$c=new ChangeSet(['tests/Unit/XTest.php','src/Integration/Northstar/X.php','apps/member-web/src/x.ts','contracts/api/x.json','src/Domain/Money.php']);$g=$c->classified();$assert(array_keys($g)===['API_CONTRACT','DOMAIN','FRONTEND','INTEGRATION','TESTING']);});
$test('review scenarios preserve required verdicts',function()use($assert){$c=new ReviewScenarioCatalog();$assert($c->get('vendor-leak')->verdict==='BLOCK'&&$c->get('sql-concatenation')->verdict==='BLOCK'&&$c->get('transfer-threshold')->verdict==='COMMENT'&&$c->get('complete-api-field')->verdict==='APPROVE'&&$c->get('raw-vendor-logging')->verdict==='BLOCK');});
$test('risk is proportional and explained',function()use($assert){$assert(ChangeRiskAssessment::assess(new ChangeSet(['README.md']))->classification==='LOW');$assert(ChangeRiskAssessment::assess(new ChangeSet(['apps/member-web/src/styles.css']))->classification==='LOW');$assert(ChangeRiskAssessment::assess(new ChangeSet(['contracts/api/member.json']))->classification==='MODERATE');$assert(ChangeRiskAssessment::assess(new ChangeSet(['src/Application/PreviewTransfer.php']))->classification==='HIGH');$assert(ChangeRiskAssessment::assess(new ChangeSet(['src/Security/SensitiveDataFlow.php']))->classification==='HIGH');});
$test('readiness blocks every mandatory failed gate',function()use($assert){$check=new DeploymentReadinessCheck();$assert($check->evaluate()->ready());foreach(['Unit tests','Architecture','Security','Contract compatibility','Git working tree'] as $gate)$assert(!$check->evaluate([$gate=>false])->ready(),$gate);});
$test('readiness scenarios include proportional docs case',function()use($assert){$check=new DeploymentReadinessCheck();$assert(!$check->evaluate(DeploymentReadinessCheck::scenario('missing-migration'))->ready());$assert($check->evaluate(DeploymentReadinessCheck::scenario('documentation-only-typo'))->ready());});
$test('git fixture parses branch status and staged files',function()use($assert){$outputs=[["feature/review\n",0],[" M README.md\nA  src/Delivery/X.php\n",0],["src/Delivery/X.php\n",0]];$i=0;$runner=function(array $args)use(&$i,$outputs){[$output,$status]=$outputs[$i++];return ['output'=>$output,'status'=>$status];};$state=(new GitRepositoryInspector('/unused',$runner))->inspect();$assert($state['branch']==='feature/review'&&!$state['clean']&&$state['changedFiles']===['README.md','src/Delivery/X.php']&&$state['stagedFiles']===['src/Delivery/X.php']);});
$test('git failures are explicit and commands are fixed argument arrays',function()use($assert){$calls=[];$runner=function(array $args)use(&$calls){$calls[]=$args;return ['output'=>'not a repository','status'=>128];};try{(new GitRepositoryInspector('/unused',$runner))->inspect();$assert(false);}catch(RuntimeException $e){$assert(str_contains($e->getMessage(),'Git inspection failed'));}$assert($calls[0]===['git','branch','--show-current']);});
$test('CI is deterministic and invokes local validation',function()use($assert){$workflow=file_get_contents(dirname(__DIR__,2).'/.github/workflows/validate.yml');$assert(str_contains($workflow,'./bin/verify')&&!preg_match('/secrets\.|northstar.*token|clearverify.*token/i',$workflow));});
$fail=0;foreach($tests as $name=>$body){try{$body();echo "PASS {$name}\n";}catch(Throwable $e){$fail++;fwrite(STDERR,"FAIL {$name}: {$e->getMessage()}\n");}}echo "\n".count($tests)." delivery tests, {$fail} failures\n";exit($fail?1:0);
