<?php
declare(strict_types=1);
require dirname(__DIR__,2).'/bootstrap.php';
use Harbor\DigitalBankingLab\Experience\{AnalyticsEvent,AnalyzeTransferFriction,AnalyzeTransferPreviewFunnel,DeviceClass,ExperienceFixture,FunnelResult};
$tests=[];$test=static function(string $n,callable $f)use(&$tests){$tests[$n]=$f;};$assert=static function(bool $v,string $m='assertion failed'){if(!$v)throw new RuntimeException($m);};
$test('analytics rejects sensitive and arbitrary properties',function()use($assert){foreach(['member_name','memberId','account_balance','transfer_amount','memo','vendor_id'] as $key){try{new AnalyticsEvent('event-000001','session-0001','page_view',new DateTimeImmutable('2026-01-01T00:00:00Z'),DeviceClass::MOBILE,'member-web',[$key=>'secret']);$assert(false,"accepted $key");}catch(InvalidArgumentException){}}});
$test('fixture IDs timestamps and sessions are deterministic',function()use($assert){$a=ExperienceFixture::events();$b=ExperienceFixture::events();$assert(serialize($a)===serialize($b)&&$a[0]->eventId==='event-000001'&&$a[0]->anonymousSessionId==='session-0001');});
$test('funnel counts conversions abandonment and ordering',function()use($assert){$r=(new AnalyzeTransferPreviewFunnel())->execute(ExperienceFixture::events());$assert(array_values($r->steps)===[100,90,85,80,74,62]);$assert($r->totalConversion()===62.0&&max($r->abandonment())===12&&array_keys($r->steps)[0]==='Member Web visit');});
$test('zero denominator is explicit',function()use($assert){$assert((new FunnelResult(['Visit'=>0,'Success'=>0]))->totalConversion()===0.0);});
$test('device comparison remains observational',function()use($assert){$a=new AnalyzeTransferPreviewFunnel();$m=$a->execute(ExperienceFixture::events(),DeviceClass::MOBILE);$d=$a->execute(ExperienceFixture::events(),DeviceClass::DESKTOP);$assert($m->steps['Member Web visit']===60&&$m->totalConversion()===50.0&&$d->steps['Member Web visit']===40&&$d->totalConversion()===80.0);$text=shell_exec(dirname(__DIR__,2).'/bin/digital-banking-lab experience-compare');$assert(str_contains((string)$text,'no causal conclusion'));});
$test('friction uses safe categories without financial values',function()use($assert){$r=(new AnalyzeTransferFriction())->execute(ExperienceFixture::events());$assert($r===['amount_format'=>3,'same_account'=>3,'insufficient_available_balance'=>1,'verification_required'=>1]);foreach(ExperienceFixture::events() as $event)$assert(array_diff(array_keys($event->properties),['error_category','destination'])===[]);});
$test('experience and SEO audits are deterministic caveated checks',function()use($assert){$audit=shell_exec(dirname(__DIR__,2).'/bin/digital-banking-lab experience-audit');$seo=shell_exec(dirname(__DIR__,2).'/bin/digital-banking-lab seo-audit');$assert(str_contains((string)$audit,'6 PASS, 1 REVIEW')&&str_contains((string)$audit,'do not replace human')&&str_contains((string)$seo,'do not predict search ranking'));});
$test('SEO source implements public metadata and private indexability',function()use($assert){$root=dirname(__DIR__,2);$member=file_get_contents($root.'/apps/member-web/index.html');$help=file_get_contents($root.'/apps/member-web/public/help/transfer-preview.html');$assert(str_contains($member,'noindex,nofollow')&&substr_count($help,'<h1>')===1&&str_contains($help,'meta name="description"')&&str_contains($help,'rel="canonical"'));});
$fail=0;foreach($tests as $name=>$body){try{$body();echo "PASS $name\n";}catch(Throwable $e){$fail++;fwrite(STDERR,"FAIL $name: {$e->getMessage()}\n");}}echo "\n".count($tests)." experience tests, $fail failures\n";exit($fail?1:0);
